name: Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: echo ${{github.ref}}

      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint fix
        run: pnpm run lint:fix

      - name: Run prettier
        run: pnpm run format

      - name: Run remark
        run: pnpm run lint:markdown

      - name: Build
        run: pnpm run build

      - name: Testing & Coverage
        run: pnpm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          registry-url: "https://registry.npmjs.org"
          scope: sebastienrousseau

      - run: pnpm install --frozen-lockfile

      - run: pnpm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set package registry
        run: pnpm config set registry https://npm.pkg.github.com

      - name: Github package registry authentication
        run: pnpm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Npm registry authentication
        run: pnpm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish the package to Github and Npm package registries
        run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
